//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.07 at 11:10:50 AM CET 
//

package com.massisframework.massis3.commons.loader.sh3d.xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "backgroundImage")
public class BackgroundImage {

	@XmlAttribute(name = "image", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String image;
	@XmlAttribute(name = "scaleDistance", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String scaleDistance;
	@XmlAttribute(name = "scaleDistanceXStart", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String scaleDistanceXStart;
	@XmlAttribute(name = "scaleDistanceYStart", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String scaleDistanceYStart;
	@XmlAttribute(name = "scaleDistanceXEnd", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String scaleDistanceXEnd;
	@XmlAttribute(name = "scaleDistanceYEnd", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String scaleDistanceYEnd;
	@XmlAttribute(name = "xOrigin")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String xOrigin;
	@XmlAttribute(name = "yOrigin")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String yOrigin;
	@XmlAttribute(name = "visible")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String visible;

	/**
	 * Gets the value of the image property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getImage()
	{
		return image;
	}

	/**
	 * Sets the value of the image property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setImage(final String value)
	{
		this.image = value;
	}

	/**
	 * Gets the value of the scaleDistance property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getScaleDistance()
	{
		return scaleDistance;
	}

	/**
	 * Sets the value of the scaleDistance property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setScaleDistance(final String value)
	{
		this.scaleDistance = value;
	}

	/**
	 * Gets the value of the scaleDistanceXStart property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getScaleDistanceXStart()
	{
		return scaleDistanceXStart;
	}

	/**
	 * Sets the value of the scaleDistanceXStart property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setScaleDistanceXStart(final String value)
	{
		this.scaleDistanceXStart = value;
	}

	/**
	 * Gets the value of the scaleDistanceYStart property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getScaleDistanceYStart()
	{
		return scaleDistanceYStart;
	}

	/**
	 * Sets the value of the scaleDistanceYStart property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setScaleDistanceYStart(final String value)
	{
		this.scaleDistanceYStart = value;
	}

	/**
	 * Gets the value of the scaleDistanceXEnd property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getScaleDistanceXEnd()
	{
		return scaleDistanceXEnd;
	}

	/**
	 * Sets the value of the scaleDistanceXEnd property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setScaleDistanceXEnd(final String value)
	{
		this.scaleDistanceXEnd = value;
	}

	/**
	 * Gets the value of the scaleDistanceYEnd property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getScaleDistanceYEnd()
	{
		return scaleDistanceYEnd;
	}

	/**
	 * Sets the value of the scaleDistanceYEnd property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setScaleDistanceYEnd(final String value)
	{
		this.scaleDistanceYEnd = value;
	}

	/**
	 * Gets the value of the xOrigin property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getXOrigin()
	{
		if (xOrigin == null)
		{
			return "0";
		} else
		{
			return xOrigin;
		}
	}

	/**
	 * Sets the value of the xOrigin property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setXOrigin(final String value)
	{
		this.xOrigin = value;
	}

	/**
	 * Gets the value of the yOrigin property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getYOrigin()
	{
		if (yOrigin == null)
		{
			return "0";
		} else
		{
			return yOrigin;
		}
	}

	/**
	 * Sets the value of the yOrigin property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setYOrigin(final String value)
	{
		this.yOrigin = value;
	}

	/**
	 * Gets the value of the visible property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getVisible()
	{
		if (visible == null)
		{
			return "true";
		} else
		{
			return visible;
		}
	}

	/**
	 * Sets the value of the visible property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setVisible(final String value)
	{
		this.visible = value;
	}

}
