//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.07 at 11:10:50 AM CET 
//

package com.massisframework.massis3.commons.loader.sh3d.xml.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
		name = "",
		propOrder = {
				"property"
		})
@XmlRootElement(name = "compass")
public class Compass {

	@XmlAttribute(name = "x", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String x;
	@XmlAttribute(name = "y", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String y;
	@XmlAttribute(name = "diameter", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String diameter;
	@XmlAttribute(name = "northDirection")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String northDirection;
	@XmlAttribute(name = "longitude")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String longitude;
	@XmlAttribute(name = "latitude")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String latitude;
	@XmlAttribute(name = "timeZone")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String timeZone;
	@XmlAttribute(name = "visible")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String visible;
	protected List<Property> property;

	/**
	 * Gets the value of the x property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getX()
	{
		return x;
	}

	/**
	 * Sets the value of the x property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setX(final String value)
	{
		this.x = value;
	}

	/**
	 * Gets the value of the y property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getY()
	{
		return y;
	}

	/**
	 * Sets the value of the y property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setY(final String value)
	{
		this.y = value;
	}

	/**
	 * Gets the value of the diameter property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDiameter()
	{
		return diameter;
	}

	/**
	 * Sets the value of the diameter property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDiameter(final String value)
	{
		this.diameter = value;
	}

	/**
	 * Gets the value of the northDirection property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNorthDirection()
	{
		if (northDirection == null)
		{
			return "0";
		} else
		{
			return northDirection;
		}
	}

	/**
	 * Sets the value of the northDirection property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNorthDirection(final String value)
	{
		this.northDirection = value;
	}

	/**
	 * Gets the value of the longitude property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLongitude()
	{
		return longitude;
	}

	/**
	 * Sets the value of the longitude property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLongitude(final String value)
	{
		this.longitude = value;
	}

	/**
	 * Gets the value of the latitude property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLatitude()
	{
		return latitude;
	}

	/**
	 * Sets the value of the latitude property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLatitude(final String value)
	{
		this.latitude = value;
	}

	/**
	 * Gets the value of the timeZone property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTimeZone()
	{
		return timeZone;
	}

	/**
	 * Sets the value of the timeZone property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTimeZone(final String value)
	{
		this.timeZone = value;
	}

	/**
	 * Gets the value of the visible property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getVisible()
	{
		if (visible == null)
		{
			return "true";
		} else
		{
			return visible;
		}
	}

	/**
	 * Sets the value of the visible property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setVisible(final String value)
	{
		this.visible = value;
	}

	/**
	 * Gets the value of the property property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the property property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getProperty().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Property
	 * }
	 * 
	 * 
	 */
	public List<Property> getProperty()
	{
		if (property == null)
		{
			property = new ArrayList<Property>();
		}
		return this.property;
	}

}
