//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.07 at 11:10:50 AM CET 
//

package com.massisframework.massis3.commons.loader.sh3d.xml.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
		name = "",
		propOrder = {
				"property",
				"textStyle"
		})
@XmlRootElement(name = "dimensionLine")
public class DimensionLine {

	@XmlAttribute(name = "level")
	@XmlIDREF
	protected Object level;
	@XmlAttribute(name = "xStart", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String xStart;
	@XmlAttribute(name = "yStart", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String yStart;
	@XmlAttribute(name = "xEnd", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String xEnd;
	@XmlAttribute(name = "yEnd", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String yEnd;
	@XmlAttribute(name = "offset", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String offset;
	protected List<Property> property;
	protected TextStyle textStyle;

	/**
	 * Gets the value of the level property.
	 * 
	 * @return possible object is {@link Object }
	 * 
	 */
	public Object getLevel()
	{
		return level;
	}

	/**
	 * Sets the value of the level property.
	 * 
	 * @param value
	 *            allowed object is {@link Object }
	 * 
	 */
	public void setLevel(final Object value)
	{
		this.level = value;
	}

	/**
	 * Gets the value of the xStart property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getXStart()
	{
		return xStart;
	}

	/**
	 * Sets the value of the xStart property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setXStart(final String value)
	{
		this.xStart = value;
	}

	/**
	 * Gets the value of the yStart property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getYStart()
	{
		return yStart;
	}

	/**
	 * Sets the value of the yStart property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setYStart(final String value)
	{
		this.yStart = value;
	}

	/**
	 * Gets the value of the xEnd property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getXEnd()
	{
		return xEnd;
	}

	/**
	 * Sets the value of the xEnd property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setXEnd(final String value)
	{
		this.xEnd = value;
	}

	/**
	 * Gets the value of the yEnd property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getYEnd()
	{
		return yEnd;
	}

	/**
	 * Sets the value of the yEnd property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setYEnd(final String value)
	{
		this.yEnd = value;
	}

	/**
	 * Gets the value of the offset property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOffset()
	{
		return offset;
	}

	/**
	 * Sets the value of the offset property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setOffset(final String value)
	{
		this.offset = value;
	}

	/**
	 * Gets the value of the property property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the property property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getProperty().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Property
	 * }
	 * 
	 * 
	 */
	public List<Property> getProperty()
	{
		if (property == null)
		{
			property = new ArrayList<Property>();
		}
		return this.property;
	}

	/**
	 * Gets the value of the textStyle property.
	 * 
	 * @return possible object is {@link TextStyle }
	 * 
	 */
	public TextStyle getTextStyle()
	{
		return textStyle;
	}

	/**
	 * Sets the value of the textStyle property.
	 * 
	 * @param value
	 *            allowed object is {@link TextStyle }
	 * 
	 */
	public void setTextStyle(final TextStyle value)
	{
		this.textStyle = value;
	}

}
