//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.07 at 11:10:50 AM CET 
//

package com.massisframework.massis3.commons.loader.sh3d.xml.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
		name = "",
		propOrder = {
				"sash",
				"property",
				"textStyle",
				"texture",
				"material"
		})
@XmlRootElement(name = "doorOrWindow")
public class DoorOrWindowXML implements FurnitureXML {

	@XmlAttribute(name = "name", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String name;
	@XmlAttribute(name = "angle")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String angle;
	@XmlAttribute(name = "visible")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String visible;
	@XmlAttribute(name = "movable")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String movable;
	@XmlAttribute(name = "description")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String description;
	@XmlAttribute(name = "modelMirrored")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String modelMirrored;
	@XmlAttribute(name = "nameVisible")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String nameVisible;
	@XmlAttribute(name = "nameAngle")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String nameAngle;
	@XmlAttribute(name = "nameXOffset")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String nameXOffset;
	@XmlAttribute(name = "nameYOffset")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String nameYOffset;
	@XmlAttribute(name = "price")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String price;
	@XmlAttribute(name = "level")
	@XmlIDREF
	protected Object level;
	@XmlAttribute(name = "catalogId")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String catalogId;
	@XmlAttribute(name = "x", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String x;
	@XmlAttribute(name = "y", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String y;
	@XmlAttribute(name = "elevation")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String elevation;
	@XmlAttribute(name = "width", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String width;
	@XmlAttribute(name = "depth", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String depth;
	@XmlAttribute(name = "height", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String height;
	@XmlAttribute(name = "dropOnTopElevation")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String dropOnTopElevation;
	@XmlAttribute(name = "information")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String information;
	@XmlAttribute(name = "model")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String model;
	@XmlAttribute(name = "icon")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String icon;
	@XmlAttribute(name = "planIcon")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String planIcon;
	@XmlAttribute(name = "modelRotation")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String modelRotation;
	@XmlAttribute(name = "backFaceShown")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String backFaceShown;
	@XmlAttribute(name = "doorOrWindow")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String doorOrWindow;
	@XmlAttribute(name = "resizable")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String resizable;
	@XmlAttribute(name = "deformable")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String deformable;
	@XmlAttribute(name = "texturable")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String texturable;
	@XmlAttribute(name = "staircaseCutOutShape")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String staircaseCutOutShape;
	@XmlAttribute(name = "color")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String color;
	@XmlAttribute(name = "shininess")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String shininess;
	@XmlAttribute(name = "creator")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String creator;
	@XmlAttribute(name = "valueAddedTaxPercentage")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String valueAddedTaxPercentage;
	@XmlAttribute(name = "currency")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String currency;
	@XmlAttribute(name = "wallThickness")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String wallThickness;
	@XmlAttribute(name = "wallDistance")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String wallDistance;
	@XmlAttribute(name = "cutOutShape")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String cutOutShape;
	@XmlAttribute(name = "boundToWall")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String boundToWall;
	protected List<Sash> sash;
	protected List<Property> property;
	protected TextStyle textStyle;
	protected TextureXML texture;
	protected List<MaterialXML> material;

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	@Override
	public String getName()
	{
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(final String value)
	{
		this.name = value;
	}

	/**
	 * Gets the value of the angle property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	@Override
	public String getAngle()
	{
		if (angle == null)
		{
			return "0";
		} else
		{
			return angle;
		}
	}

	/**
	 * Sets the value of the angle property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAngle(final String value)
	{
		this.angle = value;
	}

	/**
	 * Gets the value of the visible property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getVisible()
	{
		if (visible == null)
		{
			return "true";
		} else
		{
			return visible;
		}
	}

	/**
	 * Sets the value of the visible property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setVisible(final String value)
	{
		this.visible = value;
	}

	/**
	 * Gets the value of the movable property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMovable()
	{
		if (movable == null)
		{
			return "true";
		} else
		{
			return movable;
		}
	}

	/**
	 * Sets the value of the movable property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMovable(final String value)
	{
		this.movable = value;
	}

	/**
	 * Gets the value of the description property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDescription()
	{
		return description;
	}

	/**
	 * Sets the value of the description property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDescription(final String value)
	{
		this.description = value;
	}

	/**
	 * Gets the value of the modelMirrored property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	@Override
	public String getModelMirrored()
	{
		if (modelMirrored == null)
		{
			return "false";
		} else
		{
			return modelMirrored;
		}
	}

	/**
	 * Sets the value of the modelMirrored property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setModelMirrored(final String value)
	{
		this.modelMirrored = value;
	}

	/**
	 * Gets the value of the nameVisible property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNameVisible()
	{
		if (nameVisible == null)
		{
			return "false";
		} else
		{
			return nameVisible;
		}
	}

	/**
	 * Sets the value of the nameVisible property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNameVisible(final String value)
	{
		this.nameVisible = value;
	}

	/**
	 * Gets the value of the nameAngle property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNameAngle()
	{
		if (nameAngle == null)
		{
			return "0";
		} else
		{
			return nameAngle;
		}
	}

	/**
	 * Sets the value of the nameAngle property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNameAngle(final String value)
	{
		this.nameAngle = value;
	}

	/**
	 * Gets the value of the nameXOffset property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNameXOffset()
	{
		if (nameXOffset == null)
		{
			return "0";
		} else
		{
			return nameXOffset;
		}
	}

	/**
	 * Sets the value of the nameXOffset property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNameXOffset(final String value)
	{
		this.nameXOffset = value;
	}

	/**
	 * Gets the value of the nameYOffset property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNameYOffset()
	{
		if (nameYOffset == null)
		{
			return "0";
		} else
		{
			return nameYOffset;
		}
	}

	/**
	 * Sets the value of the nameYOffset property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNameYOffset(final String value)
	{
		this.nameYOffset = value;
	}

	/**
	 * Gets the value of the price property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPrice()
	{
		return price;
	}

	/**
	 * Sets the value of the price property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPrice(final String value)
	{
		this.price = value;
	}

	/**
	 * Gets the value of the level property.
	 * 
	 * @return possible object is {@link Object }
	 * 
	 */
	@Override
	public LevelXML getLevel()
	{
		return (LevelXML) level;
	}

	/**
	 * Sets the value of the level property.
	 * 
	 * @param value
	 *            allowed object is {@link Object }
	 * 
	 */
	public void setLevel(final Object value)
	{
		this.level = value;
	}

	/**
	 * Gets the value of the catalogId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCatalogId()
	{
		return catalogId;
	}

	/**
	 * Sets the value of the catalogId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCatalogId(final String value)
	{
		this.catalogId = value;
	}

	/**
	 * Gets the value of the x property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	@Override
	public String getX()
	{
		return x;
	}

	/**
	 * Sets the value of the x property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setX(final String value)
	{
		this.x = value;
	}

	/**
	 * Gets the value of the y property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	@Override
	public String getY()
	{
		return y;
	}

	/**
	 * Sets the value of the y property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setY(final String value)
	{
		this.y = value;
	}

	/**
	 * Gets the value of the elevation property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	@Override
	public String getElevation()
	{
		if (elevation == null)
		{
			return "0";
		} else
		{
			return elevation;
		}
	}

	/**
	 * Sets the value of the elevation property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setElevation(final String value)
	{
		this.elevation = value;
	}

	/**
	 * Gets the value of the width property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	@Override
	public String getWidth()
	{
		return width;
	}

	/**
	 * Sets the value of the width property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setWidth(final String value)
	{
		this.width = value;
	}

	/**
	 * Gets the value of the depth property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	@Override
	public String getDepth()
	{
		return depth;
	}

	/**
	 * Sets the value of the depth property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDepth(final String value)
	{
		this.depth = value;
	}

	/**
	 * Gets the value of the height property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	@Override
	public String getHeight()
	{
		return height;
	}

	/**
	 * Sets the value of the height property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setHeight(final String value)
	{
		this.height = value;
	}

	/**
	 * Gets the value of the dropOnTopElevation property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDropOnTopElevation()
	{
		if (dropOnTopElevation == null)
		{
			return "1";
		} else
		{
			return dropOnTopElevation;
		}
	}

	/**
	 * Sets the value of the dropOnTopElevation property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDropOnTopElevation(final String value)
	{
		this.dropOnTopElevation = value;
	}

	/**
	 * Gets the value of the information property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getInformation()
	{
		return information;
	}

	/**
	 * Sets the value of the information property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setInformation(final String value)
	{
		this.information = value;
	}

	/**
	 * Gets the value of the model property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	@Override
	public String getModel()
	{
		return model;
	}

	/**
	 * Sets the value of the model property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setModel(final String value)
	{
		this.model = value;
	}

	/**
	 * Gets the value of the icon property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIcon()
	{
		return icon;
	}

	/**
	 * Sets the value of the icon property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setIcon(final String value)
	{
		this.icon = value;
	}

	/**
	 * Gets the value of the planIcon property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPlanIcon()
	{
		return planIcon;
	}

	/**
	 * Sets the value of the planIcon property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPlanIcon(final String value)
	{
		this.planIcon = value;
	}

	/**
	 * Gets the value of the modelRotation property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getModelRotation()
	{
		if (modelRotation == null)
		{
			return "1 0 0 0 1 0 0 0 1";
		} else
		{
			return modelRotation;
		}
	}

	@Override
	public float[][] getModelRotationAsMatrix()
	{
		if (modelRotation == null)
			return null;
		final String[] splitted = getModelRotation().split(" ");
		final float[][] modelRot = new float[3][3];
		int k = 0;
		for (int i = 0; i < 3; i++)
		{
			for (int j = 0; j < 3; j++)
			{
				modelRot[i][j] = Float.valueOf(splitted[k++]);
			}
		}
		return modelRot;
	}

	/**
	 * Sets the value of the modelRotation property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setModelRotation(final String value)
	{
		this.modelRotation = value;
	}

	/**
	 * Gets the value of the backFaceShown property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBackFaceShown()
	{
		if (backFaceShown == null)
		{
			return "false";
		} else
		{
			return backFaceShown;
		}
	}

	/**
	 * Sets the value of the backFaceShown property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBackFaceShown(final String value)
	{
		this.backFaceShown = value;
	}

	/**
	 * Gets the value of the doorOrWindow property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDoorOrWindow()
	{
		if (doorOrWindow == null)
		{
			return "false";
		} else
		{
			return doorOrWindow;
		}
	}

	/**
	 * Sets the value of the doorOrWindow property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDoorOrWindow(final String value)
	{
		this.doorOrWindow = value;
	}

	/**
	 * Gets the value of the resizable property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getResizable()
	{
		if (resizable == null)
		{
			return "true";
		} else
		{
			return resizable;
		}
	}

	/**
	 * Sets the value of the resizable property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setResizable(final String value)
	{
		this.resizable = value;
	}

	/**
	 * Gets the value of the deformable property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDeformable()
	{
		if (deformable == null)
		{
			return "true";
		} else
		{
			return deformable;
		}
	}

	/**
	 * Sets the value of the deformable property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDeformable(final String value)
	{
		this.deformable = value;
	}

	/**
	 * Gets the value of the texturable property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTexturable()
	{
		if (texturable == null)
		{
			return "true";
		} else
		{
			return texturable;
		}
	}

	/**
	 * Sets the value of the texturable property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTexturable(final String value)
	{
		this.texturable = value;
	}

	/**
	 * Gets the value of the staircaseCutOutShape property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStaircaseCutOutShape()
	{
		return staircaseCutOutShape;
	}

	/**
	 * Sets the value of the staircaseCutOutShape property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setStaircaseCutOutShape(final String value)
	{
		this.staircaseCutOutShape = value;
	}

	/**
	 * Gets the value of the color property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getColor()
	{
		return color;
	}

	/**
	 * Sets the value of the color property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setColor(final String value)
	{
		this.color = value;
	}

	/**
	 * Gets the value of the shininess property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getShininess()
	{
		return shininess;
	}

	/**
	 * Sets the value of the shininess property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setShininess(final String value)
	{
		this.shininess = value;
	}

	/**
	 * Gets the value of the creator property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCreator()
	{
		return creator;
	}

	/**
	 * Sets the value of the creator property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCreator(final String value)
	{
		this.creator = value;
	}

	/**
	 * Gets the value of the valueAddedTaxPercentage property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getValueAddedTaxPercentage()
	{
		return valueAddedTaxPercentage;
	}

	/**
	 * Sets the value of the valueAddedTaxPercentage property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setValueAddedTaxPercentage(final String value)
	{
		this.valueAddedTaxPercentage = value;
	}

	/**
	 * Gets the value of the currency property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCurrency()
	{
		return currency;
	}

	/**
	 * Sets the value of the currency property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCurrency(final String value)
	{
		this.currency = value;
	}

	/**
	 * Gets the value of the wallThickness property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getWallThickness()
	{
		if (wallThickness == null)
		{
			return "1";
		} else
		{
			return wallThickness;
		}
	}

	/**
	 * Sets the value of the wallThickness property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setWallThickness(final String value)
	{
		this.wallThickness = value;
	}

	/**
	 * Gets the value of the wallDistance property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getWallDistance()
	{
		if (wallDistance == null)
		{
			return "0";
		} else
		{
			return wallDistance;
		}
	}

	/**
	 * Sets the value of the wallDistance property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setWallDistance(final String value)
	{
		this.wallDistance = value;
	}

	/**
	 * Gets the value of the cutOutShape property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCutOutShape()
	{
		return cutOutShape;
	}

	/**
	 * Sets the value of the cutOutShape property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCutOutShape(final String value)
	{
		this.cutOutShape = value;
	}

	/**
	 * Gets the value of the boundToWall property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBoundToWall()
	{
		if (boundToWall == null)
		{
			return "true";
		} else
		{
			return boundToWall;
		}
	}

	/**
	 * Sets the value of the boundToWall property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBoundToWall(final String value)
	{
		this.boundToWall = value;
	}

	/**
	 * Gets the value of the sash property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the sash property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getSash().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Sash }
	 * 
	 * 
	 */
	public List<Sash> getSash()
	{
		if (sash == null)
		{
			sash = new ArrayList<Sash>();
		}
		return this.sash;
	}

	/**
	 * Gets the value of the property property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the property property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getProperty().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Property
	 * }
	 * 
	 * 
	 */
	public List<Property> getProperty()
	{
		if (property == null)
		{
			property = new ArrayList<Property>();
		}
		return this.property;
	}

	/**
	 * Gets the value of the textStyle property.
	 * 
	 * @return possible object is {@link TextStyle }
	 * 
	 */
	public TextStyle getTextStyle()
	{
		return textStyle;
	}

	/**
	 * Sets the value of the textStyle property.
	 * 
	 * @param value
	 *            allowed object is {@link TextStyle }
	 * 
	 */
	public void setTextStyle(final TextStyle value)
	{
		this.textStyle = value;
	}

	/**
	 * Gets the value of the texture property.
	 * 
	 * @return possible object is {@link TextureXML }
	 * 
	 */
	public TextureXML getTexture()
	{
		return texture;
	}

	/**
	 * Sets the value of the texture property.
	 * 
	 * @param value
	 *            allowed object is {@link TextureXML }
	 * 
	 */
	public void setTexture(final TextureXML value)
	{
		this.texture = value;
	}

	/**
	 * Gets the value of the material property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the material property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getMaterial().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link MaterialXML }
	 * 
	 * 
	 */
	@Override
	public List<MaterialXML> getMaterial()
	{
		if (material == null)
		{
			material = new ArrayList<MaterialXML>();
		}
		return this.material;
	}

}
