//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.07 at 11:10:50 AM CET 
//

package com.massisframework.massis3.commons.loader.sh3d.xml.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
		name = "",
		propOrder = {
				"pieceOfFurnitureOrDoorOrWindowOrFurnitureGroupOrLight",
				"property",
				"textStyle"
		})
@XmlRootElement(name = "furnitureGroup")
public class FurnitureGroup {

	@XmlAttribute(name = "name", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String name;
	@XmlAttribute(name = "angle")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String angle;
	@XmlAttribute(name = "visible")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String visible;
	@XmlAttribute(name = "movable")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String movable;
	@XmlAttribute(name = "description")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String description;
	@XmlAttribute(name = "modelMirrored")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String modelMirrored;
	@XmlAttribute(name = "nameVisible")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String nameVisible;
	@XmlAttribute(name = "nameAngle")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String nameAngle;
	@XmlAttribute(name = "nameXOffset")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String nameXOffset;
	@XmlAttribute(name = "nameYOffset")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String nameYOffset;
	@XmlAttribute(name = "price")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String price;
	@XmlAttribute(name = "level")
	@XmlIDREF
	protected Object level;
	@XmlAttribute(name = "x")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String x;
	@XmlAttribute(name = "y")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String y;
	@XmlAttribute(name = "elevation")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String elevation;
	@XmlAttribute(name = "width")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String width;
	@XmlAttribute(name = "depth")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String depth;
	@XmlAttribute(name = "height")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String height;
	@XmlAttribute(name = "dropOnTopElevation")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String dropOnTopElevation;
	@XmlElements({
			@XmlElement(
					name = "pieceOfFurniture",
					type = PieceOfFurnitureXML.class),
			@XmlElement(name = "doorOrWindow", type = DoorOrWindowXML.class),
			@XmlElement(name = "furnitureGroup", type = FurnitureGroup.class),
			@XmlElement(name = "light", type = LightXML.class)
	})
	protected List<Object> pieceOfFurnitureOrDoorOrWindowOrFurnitureGroupOrLight;
	protected List<Property> property;
	protected TextStyle textStyle;

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(final String value)
	{
		this.name = value;
	}

	/**
	 * Gets the value of the angle property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAngle()
	{
		if (angle == null)
		{
			return "0";
		} else
		{
			return angle;
		}
	}

	/**
	 * Sets the value of the angle property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAngle(final String value)
	{
		this.angle = value;
	}

	/**
	 * Gets the value of the visible property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getVisible()
	{
		if (visible == null)
		{
			return "true";
		} else
		{
			return visible;
		}
	}

	/**
	 * Sets the value of the visible property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setVisible(final String value)
	{
		this.visible = value;
	}

	/**
	 * Gets the value of the movable property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMovable()
	{
		if (movable == null)
		{
			return "true";
		} else
		{
			return movable;
		}
	}

	/**
	 * Sets the value of the movable property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMovable(final String value)
	{
		this.movable = value;
	}

	/**
	 * Gets the value of the description property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDescription()
	{
		return description;
	}

	/**
	 * Sets the value of the description property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDescription(final String value)
	{
		this.description = value;
	}

	/**
	 * Gets the value of the modelMirrored property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getModelMirrored()
	{
		if (modelMirrored == null)
		{
			return "false";
		} else
		{
			return modelMirrored;
		}
	}

	/**
	 * Sets the value of the modelMirrored property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setModelMirrored(final String value)
	{
		this.modelMirrored = value;
	}

	/**
	 * Gets the value of the nameVisible property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNameVisible()
	{
		if (nameVisible == null)
		{
			return "false";
		} else
		{
			return nameVisible;
		}
	}

	/**
	 * Sets the value of the nameVisible property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNameVisible(final String value)
	{
		this.nameVisible = value;
	}

	/**
	 * Gets the value of the nameAngle property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNameAngle()
	{
		if (nameAngle == null)
		{
			return "0";
		} else
		{
			return nameAngle;
		}
	}

	/**
	 * Sets the value of the nameAngle property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNameAngle(final String value)
	{
		this.nameAngle = value;
	}

	/**
	 * Gets the value of the nameXOffset property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNameXOffset()
	{
		if (nameXOffset == null)
		{
			return "0";
		} else
		{
			return nameXOffset;
		}
	}

	/**
	 * Sets the value of the nameXOffset property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNameXOffset(final String value)
	{
		this.nameXOffset = value;
	}

	/**
	 * Gets the value of the nameYOffset property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNameYOffset()
	{
		if (nameYOffset == null)
		{
			return "0";
		} else
		{
			return nameYOffset;
		}
	}

	/**
	 * Sets the value of the nameYOffset property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNameYOffset(final String value)
	{
		this.nameYOffset = value;
	}

	/**
	 * Gets the value of the price property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPrice()
	{
		return price;
	}

	/**
	 * Sets the value of the price property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPrice(final String value)
	{
		this.price = value;
	}

	/**
	 * Gets the value of the level property.
	 * 
	 * @return possible object is {@link Object }
	 * 
	 */
	public Object getLevel()
	{
		return level;
	}

	/**
	 * Sets the value of the level property.
	 * 
	 * @param value
	 *            allowed object is {@link Object }
	 * 
	 */
	public void setLevel(final Object value)
	{
		this.level = value;
	}

	/**
	 * Gets the value of the x property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getX()
	{
		return x;
	}

	/**
	 * Sets the value of the x property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setX(final String value)
	{
		this.x = value;
	}

	/**
	 * Gets the value of the y property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getY()
	{
		return y;
	}

	/**
	 * Sets the value of the y property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setY(final String value)
	{
		this.y = value;
	}

	/**
	 * Gets the value of the elevation property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getElevation()
	{
		return elevation;
	}

	/**
	 * Sets the value of the elevation property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setElevation(final String value)
	{
		this.elevation = value;
	}

	/**
	 * Gets the value of the width property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getWidth()
	{
		return width;
	}

	/**
	 * Sets the value of the width property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setWidth(final String value)
	{
		this.width = value;
	}

	/**
	 * Gets the value of the depth property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDepth()
	{
		return depth;
	}

	/**
	 * Sets the value of the depth property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDepth(final String value)
	{
		this.depth = value;
	}

	/**
	 * Gets the value of the height property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getHeight()
	{
		return height;
	}

	/**
	 * Sets the value of the height property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setHeight(final String value)
	{
		this.height = value;
	}

	/**
	 * Gets the value of the dropOnTopElevation property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDropOnTopElevation()
	{
		return dropOnTopElevation;
	}

	/**
	 * Sets the value of the dropOnTopElevation property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDropOnTopElevation(final String value)
	{
		this.dropOnTopElevation = value;
	}

	/**
	 * Gets the value of the
	 * pieceOfFurnitureOrDoorOrWindowOrFurnitureGroupOrLight property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the
	 * pieceOfFurnitureOrDoorOrWindowOrFurnitureGroupOrLight property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getPieceOfFurnitureOrDoorOrWindowOrFurnitureGroupOrLight().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link PieceOfFurnitureXML } {@link DoorOrWindowXML }
	 * {@link FurnitureGroup } {@link LightXML }
	 * 
	 * 
	 */
	public List<Object> getAllFurniture()
	{
		if (pieceOfFurnitureOrDoorOrWindowOrFurnitureGroupOrLight == null)
		{
			pieceOfFurnitureOrDoorOrWindowOrFurnitureGroupOrLight = new ArrayList<Object>();
		}
		return this.pieceOfFurnitureOrDoorOrWindowOrFurnitureGroupOrLight;
	}

	/**
	 * Gets the value of the property property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the property property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getProperty().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Property
	 * }
	 * 
	 * 
	 */
	public List<Property> getProperty()
	{
		if (property == null)
		{
			property = new ArrayList<Property>();
		}
		return this.property;
	}

	/**
	 * Gets the value of the textStyle property.
	 * 
	 * @return possible object is {@link TextStyle }
	 * 
	 */
	public TextStyle getTextStyle()
	{
		return textStyle;
	}

	/**
	 * Sets the value of the textStyle property.
	 * 
	 * @param value
	 *            allowed object is {@link TextStyle }
	 * 
	 */
	public void setTextStyle(final TextStyle value)
	{
		this.textStyle = value;
	}

}
