//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.07 at 11:10:50 AM CET 
//

package com.massisframework.massis3.commons.loader.sh3d.xml.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
		name = "",
		propOrder = {
				"property",
				"furnitureVisibleProperty",
				"environment",
				"backgroundImage",
				"print",
				"compass",
				"cameraOrObserverCamera",
				"level",
				"pieceOfFurnitureOrDoorOrWindowOrFurnitureGroupOrLight",
				"wall",
				"room",
				"polyline",
				"dimensionLine",
				"label"
		})
@XmlRootElement(name = "home")
public class HomeXML {

	@XmlAttribute(name = "structure", required = false)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String structure;

	@XmlAttribute(name = "version")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String version;
	@XmlAttribute(name = "name")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String name;
	@XmlAttribute(name = "camera")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String camera;
	@XmlAttribute(name = "selectedLevel")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String selectedLevel;
	@XmlAttribute(name = "wallHeight")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String wallHeight;
	@XmlAttribute(name = "basePlanLocked")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String basePlanLocked;
	@XmlAttribute(name = "furnitureSortedProperty")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String furnitureSortedProperty;
	@XmlAttribute(name = "furnitureDescendingSorted")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String furnitureDescendingSorted;
	protected List<Property> property;
	protected List<FurnitureVisibleProperty> furnitureVisibleProperty;
	protected Environment environment;
	protected BackgroundImage backgroundImage;
	protected Print print;
	protected Compass compass;
	@XmlElements({
			@XmlElement(name = "camera", type = Camera.class),
			@XmlElement(name = "observerCamera", type = ObserverCamera.class)
	})
	protected List<Object> cameraOrObserverCamera;
	protected List<LevelXML> level;
	@XmlElements({
			@XmlElement(
					name = "pieceOfFurniture",
					type = PieceOfFurnitureXML.class),
			@XmlElement(name = "doorOrWindow", type = DoorOrWindowXML.class),
			@XmlElement(name = "furnitureGroup", type = FurnitureGroup.class),
			@XmlElement(name = "light", type = LightXML.class)
	})
	protected List<Object> pieceOfFurnitureOrDoorOrWindowOrFurnitureGroupOrLight;
	protected List<WallXML> wall;
	protected List<Room> room;
	protected List<Polyline> polyline;
	protected List<DimensionLine> dimensionLine;
	protected List<Label> label;

	/**
	 * Gets the value of the version property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getVersion()
	{
		return version;
	}

	public String getStructure()
	{
		return structure;
	}

	public void setStructure(final String structure)
	{
		this.structure = structure;
	}

	/**
	 * Sets the value of the version property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setVersion(final String value)
	{
		this.version = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(final String value)
	{
		this.name = value;
	}

	/**
	 * Gets the value of the camera property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCamera()
	{
		if (camera == null)
		{
			return "topCamera";
		} else
		{
			return camera;
		}
	}

	/**
	 * Sets the value of the camera property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCamera(final String value)
	{
		this.camera = value;
	}

	/**
	 * Gets the value of the selectedLevel property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSelectedLevel()
	{
		return selectedLevel;
	}

	/**
	 * Sets the value of the selectedLevel property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSelectedLevel(final String value)
	{
		this.selectedLevel = value;
	}

	/**
	 * Gets the value of the wallHeight property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getWallHeight()
	{
		return wallHeight;
	}

	/**
	 * Sets the value of the wallHeight property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setWallHeight(final String value)
	{
		this.wallHeight = value;
	}

	/**
	 * Gets the value of the basePlanLocked property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBasePlanLocked()
	{
		if (basePlanLocked == null)
		{
			return "false";
		} else
		{
			return basePlanLocked;
		}
	}

	/**
	 * Sets the value of the basePlanLocked property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBasePlanLocked(final String value)
	{
		this.basePlanLocked = value;
	}

	/**
	 * Gets the value of the furnitureSortedProperty property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFurnitureSortedProperty()
	{
		return furnitureSortedProperty;
	}

	/**
	 * Sets the value of the furnitureSortedProperty property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFurnitureSortedProperty(final String value)
	{
		this.furnitureSortedProperty = value;
	}

	/**
	 * Gets the value of the furnitureDescendingSorted property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFurnitureDescendingSorted()
	{
		if (furnitureDescendingSorted == null)
		{
			return "false";
		} else
		{
			return furnitureDescendingSorted;
		}
	}

	/**
	 * Sets the value of the furnitureDescendingSorted property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFurnitureDescendingSorted(final String value)
	{
		this.furnitureDescendingSorted = value;
	}

	/**
	 * Gets the value of the property property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the property property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getProperty().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Property
	 * }
	 * 
	 * 
	 */
	public List<Property> getProperty()
	{
		if (property == null)
		{
			property = new ArrayList<Property>();
		}
		return this.property;
	}

	/**
	 * Gets the value of the furnitureVisibleProperty property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the furnitureVisibleProperty property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getFurnitureVisibleProperty().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link FurnitureVisibleProperty }
	 * 
	 * 
	 */
	public List<FurnitureVisibleProperty> getFurnitureVisibleProperty()
	{
		if (furnitureVisibleProperty == null)
		{
			furnitureVisibleProperty = new ArrayList<FurnitureVisibleProperty>();
		}
		return this.furnitureVisibleProperty;
	}

	/**
	 * Gets the value of the environment property.
	 * 
	 * @return possible object is {@link Environment }
	 * 
	 */
	public Environment getEnvironment()
	{
		return environment;
	}

	/**
	 * Sets the value of the environment property.
	 * 
	 * @param value
	 *            allowed object is {@link Environment }
	 * 
	 */
	public void setEnvironment(final Environment value)
	{
		this.environment = value;
	}

	/**
	 * Gets the value of the backgroundImage property.
	 * 
	 * @return possible object is {@link BackgroundImage }
	 * 
	 */
	public BackgroundImage getBackgroundImage()
	{
		return backgroundImage;
	}

	/**
	 * Sets the value of the backgroundImage property.
	 * 
	 * @param value
	 *            allowed object is {@link BackgroundImage }
	 * 
	 */
	public void setBackgroundImage(final BackgroundImage value)
	{
		this.backgroundImage = value;
	}

	/**
	 * Gets the value of the print property.
	 * 
	 * @return possible object is {@link Print }
	 * 
	 */
	public Print getPrint()
	{
		return print;
	}

	/**
	 * Sets the value of the print property.
	 * 
	 * @param value
	 *            allowed object is {@link Print }
	 * 
	 */
	public void setPrint(final Print value)
	{
		this.print = value;
	}

	/**
	 * Gets the value of the compass property.
	 * 
	 * @return possible object is {@link Compass }
	 * 
	 */
	public Compass getCompass()
	{
		return compass;
	}

	/**
	 * Sets the value of the compass property.
	 * 
	 * @param value
	 *            allowed object is {@link Compass }
	 * 
	 */
	public void setCompass(final Compass value)
	{
		this.compass = value;
	}

	/**
	 * Gets the value of the cameraOrObserverCamera property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the cameraOrObserverCamera property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getCameraOrObserverCamera().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Camera }
	 * {@link ObserverCamera }
	 * 
	 * 
	 */
	public List<Object> getCameraOrObserverCamera()
	{
		if (cameraOrObserverCamera == null)
		{
			cameraOrObserverCamera = new ArrayList<Object>();
		}
		return this.cameraOrObserverCamera;
	}

	/**
	 * Gets the value of the level property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the level property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getLevel().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link LevelXML
	 * }
	 * 
	 * 
	 */
	public List<LevelXML> getLevel()
	{
		if (level == null)
		{
			level = new ArrayList<LevelXML>();
		}
		return this.level;
	}

	/**
	 * Gets the value of the
	 * pieceOfFurnitureOrDoorOrWindowOrFurnitureGroupOrLight property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the
	 * pieceOfFurnitureOrDoorOrWindowOrFurnitureGroupOrLight property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getPieceOfFurnitureOrDoorOrWindowOrFurnitureGroupOrLight().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link PieceOfFurnitureXML } {@link DoorOrWindowXML }
	 * {@link FurnitureGroup } {@link LightXML }
	 * 
	 * 
	 */
	public List<Object> getAllFurniture()
	{
		if (pieceOfFurnitureOrDoorOrWindowOrFurnitureGroupOrLight == null)
		{
			pieceOfFurnitureOrDoorOrWindowOrFurnitureGroupOrLight = new ArrayList<Object>();
		}
		return this.pieceOfFurnitureOrDoorOrWindowOrFurnitureGroupOrLight;
	}

	/**
	 * Gets the value of the wall property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the wall property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getWall().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link WallXML }
	 * 
	 * 
	 */
	public List<WallXML> getWall()
	{
		if (wall == null)
		{
			wall = new ArrayList<WallXML>();
		}
		return this.wall;
	}

	/**
	 * Gets the value of the room property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the room property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getRoom().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Room }
	 * 
	 * 
	 */
	public List<Room> getRoom()
	{
		if (room == null)
		{
			room = new ArrayList<Room>();
		}
		return this.room;
	}

	/**
	 * Gets the value of the polyline property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the polyline property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getPolyline().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Polyline
	 * }
	 * 
	 * 
	 */
	public List<Polyline> getPolyline()
	{
		if (polyline == null)
		{
			polyline = new ArrayList<Polyline>();
		}
		return this.polyline;
	}

	/**
	 * Gets the value of the dimensionLine property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the dimensionLine property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getDimensionLine().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link DimensionLine }
	 * 
	 * 
	 */
	public List<DimensionLine> getDimensionLine()
	{
		if (dimensionLine == null)
		{
			dimensionLine = new ArrayList<DimensionLine>();
		}
		return this.dimensionLine;
	}

	/**
	 * Gets the value of the label property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the label property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getLabel().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Label }
	 * 
	 * 
	 */
	public List<Label> getLabel()
	{
		if (label == null)
		{
			label = new ArrayList<Label>();
		}
		return this.label;
	}

}
