//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.07 at 11:10:50 AM CET 
//

package com.massisframework.massis3.commons.loader.sh3d.xml.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
		name = "",
		propOrder = {
				"property",
				"textStyle",
				"text"
		})
@XmlRootElement(name = "label")
public class Label {

	@XmlAttribute(name = "level")
	@XmlIDREF
	protected Object level;
	@XmlAttribute(name = "x", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String x;
	@XmlAttribute(name = "y", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String y;
	@XmlAttribute(name = "angle")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String angle;
	@XmlAttribute(name = "elevation")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String elevation;
	@XmlAttribute(name = "pitch")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String pitch;
	@XmlAttribute(name = "color")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String color;
	@XmlAttribute(name = "outlineColor")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String outlineColor;
	protected List<Property> property;
	protected TextStyle textStyle;
	@XmlElement(required = true)
	protected String text;

	/**
	 * Gets the value of the level property.
	 * 
	 * @return possible object is {@link Object }
	 * 
	 */
	public Object getLevel()
	{
		return level;
	}

	/**
	 * Sets the value of the level property.
	 * 
	 * @param value
	 *            allowed object is {@link Object }
	 * 
	 */
	public void setLevel(final Object value)
	{
		this.level = value;
	}

	/**
	 * Gets the value of the x property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getX()
	{
		return x;
	}

	/**
	 * Sets the value of the x property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setX(final String value)
	{
		this.x = value;
	}

	/**
	 * Gets the value of the y property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getY()
	{
		return y;
	}

	/**
	 * Sets the value of the y property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setY(final String value)
	{
		this.y = value;
	}

	/**
	 * Gets the value of the angle property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAngle()
	{
		if (angle == null)
		{
			return "0";
		} else
		{
			return angle;
		}
	}

	/**
	 * Sets the value of the angle property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAngle(final String value)
	{
		this.angle = value;
	}

	/**
	 * Gets the value of the elevation property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getElevation()
	{
		if (elevation == null)
		{
			return "0";
		} else
		{
			return elevation;
		}
	}

	/**
	 * Sets the value of the elevation property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setElevation(final String value)
	{
		this.elevation = value;
	}

	/**
	 * Gets the value of the pitch property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPitch()
	{
		return pitch;
	}

	/**
	 * Sets the value of the pitch property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPitch(final String value)
	{
		this.pitch = value;
	}

	/**
	 * Gets the value of the color property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getColor()
	{
		return color;
	}

	/**
	 * Sets the value of the color property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setColor(final String value)
	{
		this.color = value;
	}

	/**
	 * Gets the value of the outlineColor property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOutlineColor()
	{
		return outlineColor;
	}

	/**
	 * Sets the value of the outlineColor property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setOutlineColor(final String value)
	{
		this.outlineColor = value;
	}

	/**
	 * Gets the value of the property property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the property property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getProperty().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Property
	 * }
	 * 
	 * 
	 */
	public List<Property> getProperty()
	{
		if (property == null)
		{
			property = new ArrayList<Property>();
		}
		return this.property;
	}

	/**
	 * Gets the value of the textStyle property.
	 * 
	 * @return possible object is {@link TextStyle }
	 * 
	 */
	public TextStyle getTextStyle()
	{
		return textStyle;
	}

	/**
	 * Sets the value of the textStyle property.
	 * 
	 * @param value
	 *            allowed object is {@link TextStyle }
	 * 
	 */
	public void setTextStyle(final TextStyle value)
	{
		this.textStyle = value;
	}

	/**
	 * Gets the value of the text property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getText()
	{
		return text;
	}

	/**
	 * Sets the value of the text property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setText(final String value)
	{
		this.text = value;
	}

}
