//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.07 at 11:10:50 AM CET 
//

package com.massisframework.massis3.commons.loader.sh3d.xml.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
		name = "",
		propOrder = {
				"property",
				"backgroundImage"
		})
@XmlRootElement(name = "level")
public class LevelXML {

	@XmlAttribute(name = "id", required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlID
	protected String id;
	@XmlAttribute(name = "name", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String name;
	@XmlAttribute(name = "elevation", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String elevation;
	@XmlAttribute(name = "floorThickness", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String floorThickness;
	@XmlAttribute(name = "height", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String height;
	@XmlAttribute(name = "elevationIndex")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String elevationIndex;
	@XmlAttribute(name = "visible")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String visible;
	@XmlAttribute(name = "viewable")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String viewable;
	protected List<Property> property;
	protected BackgroundImage backgroundImage;

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getId()
	{
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setId(final String value)
	{
		this.id = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(final String value)
	{
		this.name = value;
	}

	/**
	 * Gets the value of the elevation property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getElevation()
	{
		return elevation;
	}

	/**
	 * Sets the value of the elevation property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setElevation(final String value)
	{
		this.elevation = value;
	}

	/**
	 * Gets the value of the floorThickness property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFloorThickness()
	{
		return floorThickness;
	}

	/**
	 * Sets the value of the floorThickness property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFloorThickness(final String value)
	{
		this.floorThickness = value;
	}

	/**
	 * Gets the value of the height property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getHeight()
	{
		return height;
	}

	/**
	 * Sets the value of the height property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setHeight(final String value)
	{
		this.height = value;
	}

	/**
	 * Gets the value of the elevationIndex property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getElevationIndex()
	{
		if (elevationIndex == null)
		{
			return "-1";
		} else
		{
			return elevationIndex;
		}
	}

	/**
	 * Sets the value of the elevationIndex property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setElevationIndex(final String value)
	{
		this.elevationIndex = value;
	}

	/**
	 * Gets the value of the visible property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getVisible()
	{
		if (visible == null)
		{
			return "true";
		} else
		{
			return visible;
		}
	}

	/**
	 * Sets the value of the visible property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setVisible(final String value)
	{
		this.visible = value;
	}

	/**
	 * Gets the value of the viewable property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getViewable()
	{
		if (viewable == null)
		{
			return "true";
		} else
		{
			return viewable;
		}
	}

	/**
	 * Sets the value of the viewable property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setViewable(final String value)
	{
		this.viewable = value;
	}

	/**
	 * Gets the value of the property property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the property property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getProperty().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Property
	 * }
	 * 
	 * 
	 */
	public List<Property> getProperty()
	{
		if (property == null)
		{
			property = new ArrayList<Property>();
		}
		return this.property;
	}

	/**
	 * Gets the value of the backgroundImage property.
	 * 
	 * @return possible object is {@link BackgroundImage }
	 * 
	 */
	public BackgroundImage getBackgroundImage()
	{
		return backgroundImage;
	}

	/**
	 * Sets the value of the backgroundImage property.
	 * 
	 * @param value
	 *            allowed object is {@link BackgroundImage }
	 * 
	 */
	public void setBackgroundImage(final BackgroundImage value)
	{
		this.backgroundImage = value;
	}

}
