//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.07 at 11:10:50 AM CET 
//

package com.massisframework.massis3.commons.loader.sh3d.xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "lightSource")
public class LightSource {

	@XmlAttribute(name = "x", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String x;
	@XmlAttribute(name = "y", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String y;
	@XmlAttribute(name = "z", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String z;
	@XmlAttribute(name = "color", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String color;
	@XmlAttribute(name = "diameter")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String diameter;

	/**
	 * Gets the value of the x property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getX()
	{
		return x;
	}

	/**
	 * Sets the value of the x property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setX(final String value)
	{
		this.x = value;
	}

	/**
	 * Gets the value of the y property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getY()
	{
		return y;
	}

	/**
	 * Sets the value of the y property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setY(final String value)
	{
		this.y = value;
	}

	/**
	 * Gets the value of the z property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getZ()
	{
		return z;
	}

	/**
	 * Sets the value of the z property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setZ(final String value)
	{
		this.z = value;
	}

	/**
	 * Gets the value of the color property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getColor()
	{
		return color;
	}

	/**
	 * Sets the value of the color property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setColor(final String value)
	{
		this.color = value;
	}

	/**
	 * Gets the value of the diameter property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDiameter()
	{
		return diameter;
	}

	/**
	 * Sets the value of the diameter property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDiameter(final String value)
	{
		this.diameter = value;
	}

}
