//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.07 at 11:10:50 AM CET 
//

package com.massisframework.massis3.commons.loader.sh3d.xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
		name = "",
		propOrder = {
				"texture"
		})
@XmlRootElement(name = "material")
public class MaterialXML {

	@XmlAttribute(name = "name", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String name;
	@XmlAttribute(name = "key")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String key;
	@XmlAttribute(name = "color")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String color;
	@XmlAttribute(name = "shininess")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String shininess;
	protected TextureXML texture;

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(final String value)
	{
		this.name = value;
	}

	/**
	 * Gets the value of the key property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getKey()
	{
		return key;
	}

	/**
	 * Sets the value of the key property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setKey(final String value)
	{
		this.key = value;
	}

	/**
	 * Gets the value of the color property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getColor()
	{
		return color;
	}

	/**
	 * Sets the value of the color property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setColor(final String value)
	{
		this.color = value;
	}

	/**
	 * Gets the value of the shininess property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getShininess()
	{
		return shininess;
	}

	/**
	 * Sets the value of the shininess property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setShininess(final String value)
	{
		this.shininess = value;
	}

	/**
	 * Gets the value of the texture property.
	 * 
	 * @return possible object is {@link TextureXML }
	 * 
	 */
	public TextureXML getTexture()
	{
		return texture;
	}

	/**
	 * Sets the value of the texture property.
	 * 
	 * @param value
	 *            allowed object is {@link TextureXML }
	 * 
	 */
	public void setTexture(final TextureXML value)
	{
		this.texture = value;
	}

	@Override
	public String toString()
	{
		return "MaterialXML [name=" + name + ", key=" + key + ", color=" + color
				+ ", shininess=" + shininess + ", texture=" + texture + "]";
	}

}
