//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.07 at 11:10:50 AM CET 
//

package com.massisframework.massis3.commons.loader.sh3d.xml.model;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the
 * com.massisframework.massis3.loader.sweethome3d.model package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package:
	 * com.massisframework.massis3.loader.sweethome3d.model
	 * 
	 */
	public ObjectFactory()
	{
	}

	/**
	 * Create an instance of {@link FurnitureGroup }
	 * 
	 */
	public FurnitureGroup createFurnitureGroup()
	{
		return new FurnitureGroup();
	}

	/**
	 * Create an instance of {@link PieceOfFurnitureXML }
	 * 
	 */
	public PieceOfFurnitureXML createPieceOfFurniture()
	{
		return new PieceOfFurnitureXML();
	}

	/**
	 * Create an instance of {@link DoorOrWindowXML }
	 * 
	 */
	public DoorOrWindowXML createDoorOrWindow()
	{
		return new DoorOrWindowXML();
	}

	/**
	 * Create an instance of {@link LightXML }
	 * 
	 */
	public LightXML createLight()
	{
		return new LightXML();
	}

	/**
	 * Create an instance of {@link Property }
	 * 
	 */
	public Property createProperty()
	{
		return new Property();
	}

	/**
	 * Create an instance of {@link TextStyle }
	 * 
	 */
	public TextStyle createTextStyle()
	{
		return new TextStyle();
	}

	/**
	 * Create an instance of {@link DimensionLine }
	 * 
	 */
	public DimensionLine createDimensionLine()
	{
		return new DimensionLine();
	}

	/**
	 * Create an instance of {@link BackgroundImage }
	 * 
	 */
	public BackgroundImage createBackgroundImage()
	{
		return new BackgroundImage();
	}

	/**
	 * Create an instance of {@link FurnitureVisibleProperty }
	 * 
	 */
	public FurnitureVisibleProperty createFurnitureVisibleProperty()
	{
		return new FurnitureVisibleProperty();
	}

	/**
	 * Create an instance of {@link TextureXML }
	 * 
	 */
	public TextureXML createTexture()
	{
		return new TextureXML();
	}

	/**
	 * Create an instance of {@link MaterialXML }
	 * 
	 */
	public MaterialXML createMaterial()
	{
		return new MaterialXML();
	}

	/**
	 * Create an instance of {@link ObserverCamera }
	 * 
	 */
	public ObserverCamera createObserverCamera()
	{
		return new ObserverCamera();
	}

	/**
	 * Create an instance of {@link Point }
	 * 
	 */
	public Point createPoint()
	{
		return new Point();
	}

	/**
	 * Create an instance of {@link Sash }
	 * 
	 */
	public Sash createSash()
	{
		return new Sash();
	}

	/**
	 * Create an instance of {@link Baseboard }
	 * 
	 */
	public Baseboard createBaseboard()
	{
		return new Baseboard();
	}

	/**
	 * Create an instance of {@link Camera }
	 * 
	 */
	public Camera createCamera()
	{
		return new Camera();
	}

	/**
	 * Create an instance of {@link LevelXML }
	 * 
	 */
	public LevelXML createLevel()
	{
		return new LevelXML();
	}

	/**
	 * Create an instance of {@link Label }
	 * 
	 */
	public Label createLabel()
	{
		return new Label();
	}

	/**
	 * Create an instance of {@link Room }
	 * 
	 */
	public Room createRoom()
	{
		return new Room();
	}

	/**
	 * Create an instance of {@link HomeXML }
	 * 
	 */
	public HomeXML createHome()
	{
		return new HomeXML();
	}

	/**
	 * Create an instance of {@link Environment }
	 * 
	 */
	public Environment createEnvironment()
	{
		return new Environment();
	}

	/**
	 * Create an instance of {@link Print }
	 * 
	 */
	public Print createPrint()
	{
		return new Print();
	}

	/**
	 * Create an instance of {@link Compass }
	 * 
	 */
	public Compass createCompass()
	{
		return new Compass();
	}

	/**
	 * Create an instance of {@link WallXML }
	 * 
	 */
	public WallXML createWall()
	{
		return new WallXML();
	}

	/**
	 * Create an instance of {@link Polyline }
	 * 
	 */
	public Polyline createPolyline()
	{
		return new Polyline();
	}

	/**
	 * Create an instance of {@link LightSource }
	 * 
	 */
	public LightSource createLightSource()
	{
		return new LightSource();
	}

}
