//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.07 at 11:10:50 AM CET 
//

package com.massisframework.massis3.commons.loader.sh3d.xml.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
		name = "",
		propOrder = {
				"property"
		})
@XmlRootElement(name = "observerCamera")
public class ObserverCamera {

	@XmlAttribute(name = "name")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String name;
	@XmlAttribute(name = "lens")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String lens;
	@XmlAttribute(name = "x", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String x;
	@XmlAttribute(name = "y", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String y;
	@XmlAttribute(name = "z", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String z;
	@XmlAttribute(name = "yaw", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String yaw;
	@XmlAttribute(name = "pitch", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String pitch;
	@XmlAttribute(name = "time")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String time;
	@XmlAttribute(name = "fieldOfView", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String fieldOfView;
	@XmlAttribute(name = "attribute", required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String attribute;
	@XmlAttribute(name = "fixedSize")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String fixedSize;
	protected List<Property> property;

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(final String value)
	{
		this.name = value;
	}

	/**
	 * Gets the value of the lens property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLens()
	{
		if (lens == null)
		{
			return "PINHOLE";
		} else
		{
			return lens;
		}
	}

	/**
	 * Sets the value of the lens property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLens(final String value)
	{
		this.lens = value;
	}

	/**
	 * Gets the value of the x property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getX()
	{
		return x;
	}

	/**
	 * Sets the value of the x property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setX(final String value)
	{
		this.x = value;
	}

	/**
	 * Gets the value of the y property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getY()
	{
		return y;
	}

	/**
	 * Sets the value of the y property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setY(final String value)
	{
		this.y = value;
	}

	/**
	 * Gets the value of the z property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getZ()
	{
		return z;
	}

	/**
	 * Sets the value of the z property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setZ(final String value)
	{
		this.z = value;
	}

	/**
	 * Gets the value of the yaw property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getYaw()
	{
		return yaw;
	}

	/**
	 * Sets the value of the yaw property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setYaw(final String value)
	{
		this.yaw = value;
	}

	/**
	 * Gets the value of the pitch property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPitch()
	{
		return pitch;
	}

	/**
	 * Sets the value of the pitch property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPitch(final String value)
	{
		this.pitch = value;
	}

	/**
	 * Gets the value of the time property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTime()
	{
		return time;
	}

	/**
	 * Sets the value of the time property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTime(final String value)
	{
		this.time = value;
	}

	/**
	 * Gets the value of the fieldOfView property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFieldOfView()
	{
		return fieldOfView;
	}

	/**
	 * Sets the value of the fieldOfView property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFieldOfView(final String value)
	{
		this.fieldOfView = value;
	}

	/**
	 * Gets the value of the attribute property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAttribute()
	{
		return attribute;
	}

	/**
	 * Sets the value of the attribute property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAttribute(final String value)
	{
		this.attribute = value;
	}

	/**
	 * Gets the value of the fixedSize property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFixedSize()
	{
		if (fixedSize == null)
		{
			return "false";
		} else
		{
			return fixedSize;
		}
	}

	/**
	 * Sets the value of the fixedSize property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFixedSize(final String value)
	{
		this.fixedSize = value;
	}

	/**
	 * Gets the value of the property property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the property property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getProperty().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Property
	 * }
	 * 
	 * 
	 */
	public List<Property> getProperty()
	{
		if (property == null)
		{
			property = new ArrayList<Property>();
		}
		return this.property;
	}

}
