//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.07 at 11:10:50 AM CET 
//

package com.massisframework.massis3.commons.loader.sh3d.xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "print")
public class Print {

	@XmlAttribute(name = "headerFormat")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String headerFormat;
	@XmlAttribute(name = "footerFormat")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String footerFormat;
	@XmlAttribute(name = "planScale")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String planScale;
	@XmlAttribute(name = "furniturePrinted")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String furniturePrinted;
	@XmlAttribute(name = "planPrinted")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String planPrinted;
	@XmlAttribute(name = "view3DPrinted")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String view3DPrinted;
	@XmlAttribute(name = "paperWidth", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String paperWidth;
	@XmlAttribute(name = "paperHeight", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String paperHeight;
	@XmlAttribute(name = "paperTopMargin", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String paperTopMargin;
	@XmlAttribute(name = "paperLeftMargin", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String paperLeftMargin;
	@XmlAttribute(name = "paperBottomMargin", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String paperBottomMargin;
	@XmlAttribute(name = "paperRightMargin", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String paperRightMargin;
	@XmlAttribute(name = "paperOrientation", required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String paperOrientation;

	/**
	 * Gets the value of the headerFormat property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getHeaderFormat()
	{
		return headerFormat;
	}

	/**
	 * Sets the value of the headerFormat property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setHeaderFormat(final String value)
	{
		this.headerFormat = value;
	}

	/**
	 * Gets the value of the footerFormat property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFooterFormat()
	{
		return footerFormat;
	}

	/**
	 * Sets the value of the footerFormat property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFooterFormat(final String value)
	{
		this.footerFormat = value;
	}

	/**
	 * Gets the value of the planScale property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPlanScale()
	{
		return planScale;
	}

	/**
	 * Sets the value of the planScale property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPlanScale(final String value)
	{
		this.planScale = value;
	}

	/**
	 * Gets the value of the furniturePrinted property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFurniturePrinted()
	{
		if (furniturePrinted == null)
		{
			return "true";
		} else
		{
			return furniturePrinted;
		}
	}

	/**
	 * Sets the value of the furniturePrinted property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFurniturePrinted(final String value)
	{
		this.furniturePrinted = value;
	}

	/**
	 * Gets the value of the planPrinted property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPlanPrinted()
	{
		if (planPrinted == null)
		{
			return "true";
		} else
		{
			return planPrinted;
		}
	}

	/**
	 * Sets the value of the planPrinted property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPlanPrinted(final String value)
	{
		this.planPrinted = value;
	}

	/**
	 * Gets the value of the view3DPrinted property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getView3DPrinted()
	{
		if (view3DPrinted == null)
		{
			return "true";
		} else
		{
			return view3DPrinted;
		}
	}

	/**
	 * Sets the value of the view3DPrinted property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setView3DPrinted(final String value)
	{
		this.view3DPrinted = value;
	}

	/**
	 * Gets the value of the paperWidth property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPaperWidth()
	{
		return paperWidth;
	}

	/**
	 * Sets the value of the paperWidth property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPaperWidth(final String value)
	{
		this.paperWidth = value;
	}

	/**
	 * Gets the value of the paperHeight property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPaperHeight()
	{
		return paperHeight;
	}

	/**
	 * Sets the value of the paperHeight property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPaperHeight(final String value)
	{
		this.paperHeight = value;
	}

	/**
	 * Gets the value of the paperTopMargin property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPaperTopMargin()
	{
		return paperTopMargin;
	}

	/**
	 * Sets the value of the paperTopMargin property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPaperTopMargin(final String value)
	{
		this.paperTopMargin = value;
	}

	/**
	 * Gets the value of the paperLeftMargin property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPaperLeftMargin()
	{
		return paperLeftMargin;
	}

	/**
	 * Sets the value of the paperLeftMargin property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPaperLeftMargin(final String value)
	{
		this.paperLeftMargin = value;
	}

	/**
	 * Gets the value of the paperBottomMargin property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPaperBottomMargin()
	{
		return paperBottomMargin;
	}

	/**
	 * Sets the value of the paperBottomMargin property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPaperBottomMargin(final String value)
	{
		this.paperBottomMargin = value;
	}

	/**
	 * Gets the value of the paperRightMargin property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPaperRightMargin()
	{
		return paperRightMargin;
	}

	/**
	 * Sets the value of the paperRightMargin property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPaperRightMargin(final String value)
	{
		this.paperRightMargin = value;
	}

	/**
	 * Gets the value of the paperOrientation property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPaperOrientation()
	{
		return paperOrientation;
	}

	/**
	 * Sets the value of the paperOrientation property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPaperOrientation(final String value)
	{
		this.paperOrientation = value;
	}

}
