//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.07 at 11:10:50 AM CET 
//

package com.massisframework.massis3.commons.loader.sh3d.xml.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
		name = "",
		propOrder = {
				"propertyOrTextStyleOrTextureOrPoint"
		})
@XmlRootElement(name = "room")
public class Room {

	@XmlAttribute(name = "level")
	@XmlIDREF
	protected Object level;

	@XmlAttribute(name = "name")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String name;
	@XmlAttribute(name = "nameAngle")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String nameAngle;
	@XmlAttribute(name = "nameXOffset")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String nameXOffset;
	@XmlAttribute(name = "nameYOffset")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String nameYOffset;
	@XmlAttribute(name = "areaVisible")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String areaVisible;
	@XmlAttribute(name = "areaAngle")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String areaAngle;
	@XmlAttribute(name = "areaXOffset")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String areaXOffset;
	@XmlAttribute(name = "areaYOffset")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String areaYOffset;
	@XmlAttribute(name = "floorVisible")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String floorVisible;
	@XmlAttribute(name = "floorColor")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String floorColor;
	@XmlAttribute(name = "floorShininess")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String floorShininess;
	@XmlAttribute(name = "ceilingVisible")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String ceilingVisible;
	@XmlAttribute(name = "ceilingColor")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String ceilingColor;
	@XmlAttribute(name = "ceilingShininess")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String ceilingShininess;
	@XmlElements({
			@XmlElement(name = "property", type = Property.class),
			@XmlElement(name = "textStyle", type = TextStyle.class),
			@XmlElement(name = "texture", type = TextureXML.class),
			@XmlElement(name = "point", type = Point.class)
	})
	protected List<Object> propertyOrTextStyleOrTextureOrPoint;

	/**
	 * Gets the value of the level property.
	 * 
	 * @return possible object is {@link Object }
	 * 
	 */
	public Object getLevel()
	{
		return level;
	}

	/**
	 * Sets the value of the level property.
	 * 
	 * @param value
	 *            allowed object is {@link Object }
	 * 
	 */
	public void setLevel(final Object value)
	{
		this.level = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(final String value)
	{
		this.name = value;
	}

	/**
	 * Gets the value of the nameAngle property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNameAngle()
	{
		if (nameAngle == null)
		{
			return "0";
		} else
		{
			return nameAngle;
		}
	}

	/**
	 * Sets the value of the nameAngle property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNameAngle(final String value)
	{
		this.nameAngle = value;
	}

	/**
	 * Gets the value of the nameXOffset property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNameXOffset()
	{
		if (nameXOffset == null)
		{
			return "0";
		} else
		{
			return nameXOffset;
		}
	}

	/**
	 * Sets the value of the nameXOffset property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNameXOffset(final String value)
	{
		this.nameXOffset = value;
	}

	/**
	 * Gets the value of the nameYOffset property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNameYOffset()
	{
		if (nameYOffset == null)
		{
			return "-40";
		} else
		{
			return nameYOffset;
		}
	}

	/**
	 * Sets the value of the nameYOffset property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNameYOffset(final String value)
	{
		this.nameYOffset = value;
	}

	/**
	 * Gets the value of the areaVisible property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAreaVisible()
	{
		if (areaVisible == null)
		{
			return "false";
		} else
		{
			return areaVisible;
		}
	}

	/**
	 * Sets the value of the areaVisible property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAreaVisible(final String value)
	{
		this.areaVisible = value;
	}

	/**
	 * Gets the value of the areaAngle property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAreaAngle()
	{
		if (areaAngle == null)
		{
			return "0";
		} else
		{
			return areaAngle;
		}
	}

	/**
	 * Sets the value of the areaAngle property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAreaAngle(final String value)
	{
		this.areaAngle = value;
	}

	/**
	 * Gets the value of the areaXOffset property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAreaXOffset()
	{
		if (areaXOffset == null)
		{
			return "0";
		} else
		{
			return areaXOffset;
		}
	}

	/**
	 * Sets the value of the areaXOffset property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAreaXOffset(final String value)
	{
		this.areaXOffset = value;
	}

	/**
	 * Gets the value of the areaYOffset property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAreaYOffset()
	{
		if (areaYOffset == null)
		{
			return "0";
		} else
		{
			return areaYOffset;
		}
	}

	/**
	 * Sets the value of the areaYOffset property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAreaYOffset(final String value)
	{
		this.areaYOffset = value;
	}

	/**
	 * Gets the value of the floorVisible property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFloorVisible()
	{
		if (floorVisible == null)
		{
			return "true";
		} else
		{
			return floorVisible;
		}
	}

	/**
	 * Sets the value of the floorVisible property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFloorVisible(final String value)
	{
		this.floorVisible = value;
	}

	/**
	 * Gets the value of the floorColor property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFloorColor()
	{
		return floorColor;
	}

	/**
	 * Sets the value of the floorColor property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFloorColor(final String value)
	{
		this.floorColor = value;
	}

	/**
	 * Gets the value of the floorShininess property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFloorShininess()
	{
		if (floorShininess == null)
		{
			return "0";
		} else
		{
			return floorShininess;
		}
	}

	/**
	 * Sets the value of the floorShininess property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFloorShininess(final String value)
	{
		this.floorShininess = value;
	}

	/**
	 * Gets the value of the ceilingVisible property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCeilingVisible()
	{
		if (ceilingVisible == null)
		{
			return "true";
		} else
		{
			return ceilingVisible;
		}
	}

	/**
	 * Sets the value of the ceilingVisible property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCeilingVisible(final String value)
	{
		this.ceilingVisible = value;
	}

	/**
	 * Gets the value of the ceilingColor property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCeilingColor()
	{
		return ceilingColor;
	}

	/**
	 * Sets the value of the ceilingColor property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCeilingColor(final String value)
	{
		this.ceilingColor = value;
	}

	/**
	 * Gets the value of the ceilingShininess property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCeilingShininess()
	{
		if (ceilingShininess == null)
		{
			return "0";
		} else
		{
			return ceilingShininess;
		}
	}

	/**
	 * Sets the value of the ceilingShininess property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCeilingShininess(final String value)
	{
		this.ceilingShininess = value;
	}

	/**
	 * Gets the value of the propertyOrTextStyleOrTextureOrPoint property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the propertyOrTextStyleOrTextureOrPoint
	 * property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getPropertyOrTextStyleOrTextureOrPoint().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Property
	 * } {@link TextStyle } {@link TextureXML } {@link Point }
	 * 
	 * 
	 */
	public List<Object> getPropertyOrTextStyleOrTextureOrPoint()
	{
		if (propertyOrTextStyleOrTextureOrPoint == null)
		{
			propertyOrTextStyleOrTextureOrPoint = new ArrayList<Object>();
		}
		return this.propertyOrTextStyleOrTextureOrPoint;
	}
}
