//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.07 at 11:10:50 AM CET 
//

package com.massisframework.massis3.commons.loader.sh3d.xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "sash")
public class Sash {

	@XmlAttribute(name = "xAxis", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String xAxis;
	@XmlAttribute(name = "yAxis", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String yAxis;
	@XmlAttribute(name = "width", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String width;
	@XmlAttribute(name = "startAngle", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String startAngle;
	@XmlAttribute(name = "endAngle", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String endAngle;

	/**
	 * Gets the value of the xAxis property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getXAxis()
	{
		return xAxis;
	}

	/**
	 * Sets the value of the xAxis property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setXAxis(final String value)
	{
		this.xAxis = value;
	}

	/**
	 * Gets the value of the yAxis property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getYAxis()
	{
		return yAxis;
	}

	/**
	 * Sets the value of the yAxis property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setYAxis(final String value)
	{
		this.yAxis = value;
	}

	/**
	 * Gets the value of the width property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getWidth()
	{
		return width;
	}

	/**
	 * Sets the value of the width property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setWidth(final String value)
	{
		this.width = value;
	}

	/**
	 * Gets the value of the startAngle property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStartAngle()
	{
		return startAngle;
	}

	/**
	 * Sets the value of the startAngle property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setStartAngle(final String value)
	{
		this.startAngle = value;
	}

	/**
	 * Gets the value of the endAngle property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEndAngle()
	{
		return endAngle;
	}

	/**
	 * Sets the value of the endAngle property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEndAngle(final String value)
	{
		this.endAngle = value;
	}

}
