//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.07 at 11:10:50 AM CET 
//

package com.massisframework.massis3.commons.loader.sh3d.xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "texture")
public class TextureXML {

	@XmlAttribute(name = "attribute")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String attribute;
	@XmlAttribute(name = "catalogId")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String catalogId;
	@XmlAttribute(name = "name", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String name;
	@XmlAttribute(name = "width", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String width;
	@XmlAttribute(name = "height", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String height;
	@XmlAttribute(name = "angle")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String angle;
	@XmlAttribute(name = "leftToRightOriented")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String leftToRightOriented;
	@XmlAttribute(name = "image", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String image;

	/**
	 * Gets the value of the attribute property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAttribute()
	{
		return attribute;
	}

	/**
	 * Sets the value of the attribute property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAttribute(final String value)
	{
		this.attribute = value;
	}

	/**
	 * Gets the value of the catalogId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCatalogId()
	{
		return catalogId;
	}

	/**
	 * Sets the value of the catalogId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCatalogId(final String value)
	{
		this.catalogId = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(final String value)
	{
		this.name = value;
	}

	/**
	 * Gets the value of the width property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getWidth()
	{
		return width;
	}

	/**
	 * Sets the value of the width property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setWidth(final String value)
	{
		this.width = value;
	}

	/**
	 * Gets the value of the height property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getHeight()
	{
		return height;
	}

	/**
	 * Sets the value of the height property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setHeight(final String value)
	{
		this.height = value;
	}

	/**
	 * Gets the value of the angle property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAngle()
	{
		if (angle == null)
		{
			return "0";
		} else
		{
			return angle;
		}
	}

	/**
	 * Sets the value of the angle property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAngle(final String value)
	{
		this.angle = value;
	}

	/**
	 * Gets the value of the leftToRightOriented property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLeftToRightOriented()
	{
		if (leftToRightOriented == null)
		{
			return "true";
		} else
		{
			return leftToRightOriented;
		}
	}

	/**
	 * Sets the value of the leftToRightOriented property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLeftToRightOriented(final String value)
	{
		this.leftToRightOriented = value;
	}

	/**
	 * Gets the value of the image property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getImage()
	{
		return image;
	}

	/**
	 * Sets the value of the image property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setImage(final String value)
	{
		this.image = value;
	}

}
