//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.07 at 11:10:50 AM CET 
//

package com.massisframework.massis3.commons.loader.sh3d.xml.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
		name = "",
		propOrder = {
				"propertyOrTextureOrBaseboard"
		})
@XmlRootElement(name = "wall")
public class WallXML {

	@XmlAttribute(name = "id", required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlID
	protected String id;

	@XmlAttribute(name = "level")
	@XmlIDREF
	protected Object level;
	@XmlAttribute(name = "wallAtStart")
	@XmlIDREF
	protected Object wallAtStart;
	@XmlAttribute(name = "wallAtEnd")
	@XmlIDREF
	protected Object wallAtEnd;
	@XmlAttribute(name = "xStart", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String xStart;
	@XmlAttribute(name = "yStart", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String yStart;
	@XmlAttribute(name = "xEnd", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String xEnd;
	@XmlAttribute(name = "yEnd", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String yEnd;
	@XmlAttribute(name = "height")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String height;
	@XmlAttribute(name = "heightAtEnd")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String heightAtEnd;
	@XmlAttribute(name = "thickness", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String thickness;
	@XmlAttribute(name = "arcExtent")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String arcExtent;
	@XmlAttribute(name = "pattern")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String pattern;
	@XmlAttribute(name = "topColor")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String topColor;
	@XmlAttribute(name = "leftSideColor")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String leftSideColor;
	@XmlAttribute(name = "leftSideShininess")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String leftSideShininess;
	@XmlAttribute(name = "rightSideColor")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String rightSideColor;
	@XmlAttribute(name = "rightSideShininess")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String rightSideShininess;
	@XmlElements({
			@XmlElement(name = "property", type = Property.class),
			@XmlElement(name = "texture", type = TextureXML.class),
			@XmlElement(name = "baseboard", type = Baseboard.class)
	})
	protected List<Object> propertyOrTextureOrBaseboard;

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getId()
	{
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setId(final String value)
	{
		this.id = value;
	}

	/**
	 * Gets the value of the level property.
	 * 
	 * @return possible object is {@link Object }
	 * 
	 */
	public Object getLevel()
	{
		return level;
	}

	/**
	 * Sets the value of the level property.
	 * 
	 * @param value
	 *            allowed object is {@link Object }
	 * 
	 */
	public void setLevel(final Object value)
	{
		this.level = value;
	}

	/**
	 * Gets the value of the wallAtStart property.
	 * 
	 * @return possible object is {@link Object }
	 * 
	 */
	public Object getWallAtStart()
	{
		return wallAtStart;
	}

	/**
	 * Sets the value of the wallAtStart property.
	 * 
	 * @param value
	 *            allowed object is {@link Object }
	 * 
	 */
	public void setWallAtStart(final Object value)
	{
		this.wallAtStart = value;
	}

	/**
	 * Gets the value of the wallAtEnd property.
	 * 
	 * @return possible object is {@link Object }
	 * 
	 */
	public Object getWallAtEnd()
	{
		return wallAtEnd;
	}

	/**
	 * Sets the value of the wallAtEnd property.
	 * 
	 * @param value
	 *            allowed object is {@link Object }
	 * 
	 */
	public void setWallAtEnd(final Object value)
	{
		this.wallAtEnd = value;
	}

	/**
	 * Gets the value of the xStart property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getXStart()
	{
		return xStart;
	}

	/**
	 * Sets the value of the xStart property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setXStart(final String value)
	{
		this.xStart = value;
	}

	/**
	 * Gets the value of the yStart property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getYStart()
	{
		return yStart;
	}

	/**
	 * Sets the value of the yStart property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setYStart(final String value)
	{
		this.yStart = value;
	}

	/**
	 * Gets the value of the xEnd property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getXEnd()
	{
		return xEnd;
	}

	/**
	 * Sets the value of the xEnd property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setXEnd(final String value)
	{
		this.xEnd = value;
	}

	/**
	 * Gets the value of the yEnd property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getYEnd()
	{
		return yEnd;
	}

	/**
	 * Sets the value of the yEnd property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setYEnd(final String value)
	{
		this.yEnd = value;
	}

	/**
	 * Gets the value of the height property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getHeight()
	{
		return height;
	}

	/**
	 * Sets the value of the height property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setHeight(final String value)
	{
		this.height = value;
	}

	/**
	 * Gets the value of the heightAtEnd property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getHeightAtEnd()
	{
		return heightAtEnd;
	}

	/**
	 * Sets the value of the heightAtEnd property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setHeightAtEnd(final String value)
	{
		this.heightAtEnd = value;
	}

	/**
	 * Gets the value of the thickness property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getThickness()
	{
		return thickness;
	}

	/**
	 * Sets the value of the thickness property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setThickness(final String value)
	{
		this.thickness = value;
	}

	/**
	 * Gets the value of the arcExtent property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getArcExtent()
	{
		return arcExtent;
	}

	/**
	 * Sets the value of the arcExtent property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setArcExtent(final String value)
	{
		this.arcExtent = value;
	}

	/**
	 * Gets the value of the pattern property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPattern()
	{
		return pattern;
	}

	/**
	 * Sets the value of the pattern property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPattern(final String value)
	{
		this.pattern = value;
	}

	/**
	 * Gets the value of the topColor property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTopColor()
	{
		return topColor;
	}

	/**
	 * Sets the value of the topColor property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTopColor(final String value)
	{
		this.topColor = value;
	}

	/**
	 * Gets the value of the leftSideColor property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLeftSideColor()
	{
		return leftSideColor;
	}

	/**
	 * Sets the value of the leftSideColor property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLeftSideColor(final String value)
	{
		this.leftSideColor = value;
	}

	/**
	 * Gets the value of the leftSideShininess property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLeftSideShininess()
	{
		if (leftSideShininess == null)
		{
			return "0";
		} else
		{
			return leftSideShininess;
		}
	}

	/**
	 * Sets the value of the leftSideShininess property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLeftSideShininess(final String value)
	{
		this.leftSideShininess = value;
	}

	/**
	 * Gets the value of the rightSideColor property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRightSideColor()
	{
		return rightSideColor;
	}

	/**
	 * Sets the value of the rightSideColor property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRightSideColor(final String value)
	{
		this.rightSideColor = value;
	}

	/**
	 * Gets the value of the rightSideShininess property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRightSideShininess()
	{
		if (rightSideShininess == null)
		{
			return "0";
		} else
		{
			return rightSideShininess;
		}
	}

	/**
	 * Sets the value of the rightSideShininess property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRightSideShininess(final String value)
	{
		this.rightSideShininess = value;
	}

	/**
	 * Gets the value of the propertyOrTextureOrBaseboard property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the propertyOrTextureOrBaseboard property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getPropertyOrTextureOrBaseboard().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Property
	 * } {@link TextureXML } {@link Baseboard }
	 * 
	 * 
	 */
	public List<Object> getPropertyOrTextureOrBaseboard()
	{
		if (propertyOrTextureOrBaseboard == null)
		{
			propertyOrTextureOrBaseboard = new ArrayList<Object>();
		}
		return this.propertyOrTextureOrBaseboard;
	}

}
